### ISSUE TITLE
Config - locales - fallback - default value

### ISSUE THREAD

**Issue by solcik** [contributte/translation#5] opened 2019-05-16 22:54 UTC
Hello,

There is the default value for fallback in the configuration set to `en_US`  on this line:

https://github.com/contributte/translation/blob/master/src/di/TranslationExtension.php#L39

I thought that when I specify my fallback I would overwrite the default one, but it is not the case.

```neon
extensions:
    contributte.translation: Contributte\Translation\DI\TranslationExtension

contributte.translation:
    debug: %debugMode%
    locales:
        whitelist: %languages%
        default: %languages.0%
        fallback:
            - cs_CZ
            - cs
    dirs:
        - %rootDir%/src/resources/lang
```

It got my eye when I was checking the output of cache file. I did not expect `en_US` to be there at all. There should be only `de` and `cs`, but not `en`.

```php
<?php

use Symfony\Component\Translation\MessageCatalogue;

$catalogue = new MessageCatalogue('de', array ());
$catalogueDe_DE = new MessageCatalogue('de_DE', array ());
$catalogue->addFallbackCatalogue($catalogueDe_DE);
$catalogueEn_US = new MessageCatalogue('en_US', array ());
$catalogueDe_DE->addFallbackCatalogue($catalogueEn_US);
$catalogueCs_CZ = new MessageCatalogue('cs_CZ', array ());
$catalogueEn_US->addFallbackCatalogue($catalogueCs_CZ);
$catalogueCs = new MessageCatalogue('cs', array ());
$catalogueCs_CZ->addFallbackCatalogue($catalogueCs);

return $catalogue;
```

I debugged it and found out, that it is working as expected since nette\schema is working that way as per https://github.com/nette/schema/blob/master/tests/Schema/Expect.array.phpt#L46

**So I suggest removing the default value for the fallback array.**

**Comment by aleswita** [comment] 2019-05-17 14:39
I think you are right, that translator can not be any default value about language set.

So may be removed and make this option are required.. 


Temporary solution for you:
```php
fallback!:
    - cs_CZ
    - cs

**Comment by mabar** [comment] 2019-05-17 15:08
Just set fallback if none given, outside of Schema structure. Given array is merged with default array by keys, so it cannot work as intended.

Maybe could @dg consider it as a new feature? 
```php
Expect::array()->if(function (array $value): bool {
	return empty($value);
})->default([]);
// or
Expect::array()->conditional(function (Type $type, array $value): void {
	if (empty($value)) {
		$type->default([]);
	}
});
```

@aleswita Also [`localeResolvers`](https://github.com/contributte/translation/blob/ae5632cbe2cb07c248ae55ff650e6291decbc7ae/src/di/TranslationExtension.php#L41) should be modified.

**Comment by aleswita** [comment] 2019-05-24 11:09
@solcik fixed by https://github.com/contributte/translation/commit/7950007bf31eba18699c8af90ca24b13cff5e862

**Closed by aleswita** 2019-05-24 11:09 UTC
